blank_issues_enabled: false   # hides the default "Open a blank issue" option

contact_links:
  - name: ❓ Questions / Help
    url: https://github.com/<your-username>/<your-repo>/discussions
    about: Please ask questions in Discussions, not as issues.
